### ISSUE TITLE
General - Add applicable testing

### ISSUE THREAD

**Issue by rickleegit** [department-of-veterans-affairs/gi-bill-comparison-tool#198] opened 2015-11-20 13:03 UTC
@mphprogrammer just adding this so we don't forget and let this slip. CC'ing @plusjeff to seek guidance.

**Comment by rickleegit** [comment] 2016-03-11 15:29
OK to close this issue?

**Comment by mphprogrammer** [comment] 2016-03-11 15:30
No.

**Comment by mphprogrammer** [comment] 2017-03-14 16:33
We can close this... duplicate of 254.

**Closed** 2017-03-14 16:33 UTC
Labels: backlog
