### ISSUE TITLE
URGENT: New Caution Flag (New Tool Tip and  Anchor for Ashford University- Online)

### ISSUE THREAD

**Issue by NobleDon** [department-of-veterans-affairs/gi-bill-comparison-tool#477] opened 2017-11-15 15:45 UTC
EDU Service is requesting to add new Tool Tip to the Caution Flags section, also we are providing you the new Anchor for that Tool Tip:

**Ashford University Online** 
Facility Code:  21007103

The following caution flag is being add to this school:
"VA has notified Ashford that benefit payments may be suspended as early as January 8, 2018, unless corrective actions are taken"

Education Service will need the above caution flag add to the Tool Tips.

The following below is the Anchor is the new Caution Flag Tool Tip:
https://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp#AshfordSAA

 EDU Service deadline for update is Thursday, November 16, 2017.

**Comment by saneshark** [comment] 2017-11-16 17:43
@NobleDon 

Adding the new caution flag is a data change that would most likely happen in the settlements.csv
I'm probably looking at an outdated version of this CSV, but approximately around line 861 in that file, there is the following currently:

```CSV
154022,ASHFORD UNIVERSITY,,,Potential lapse in program approval and payment of GI Bill benefits,06/01/2016,https://www.iowaattorneygeneral.gov/newsroom/ashford-university-and-parent-company-bridgepoint-education-agree-to-7-25-million-payment-and-majo
```

So I'm thinking if you modify the settlements.csv file, upload the new file, and generate a new build of the data service you should get the changes you want.

That being said, I noticed the list of cautionary warnings that we link to in the "Learn More About These Warnings" section [found here](https://www.vets.gov/gi-bill-comparison-tool/profile/21007103#accordion-item-14) is getting a bit long (you might need to scroll down until you see the following).

<img width="1028" alt="screen shot 2017-11-16 at 9 45 52 am" src="https://user-images.githubusercontent.com/591737/32906881-25e923a2-cab3-11e7-810e-437225655548.png">

I can't recall if this list is automatically generated by our F/E or not so adding the link there might require some changes on our side that we'd need to coordinate. Regardless, that list is getting quite long. 

<img width="588" alt="screen shot 2017-11-16 at 9 47 51 am" src="https://user-images.githubusercontent.com/591737/32906930-3fbdd566-cab3-11e7-9c46-4cb9af370729.png">


Longer term it would be nice if the list only included cautionary details for those specific to the institution being referenced. @U-DON @bshyong tagging you here.

If we find that the changes require manual intervention, the earliest we could get to this change would be sometime in our next development sprint. At that point we could make the appropriate coding changes, test, and have this out for you. In the meantime I see two options.

1. Go ahead and make the modifications to the settlements.csv and get the cautionary flag out there for this institution *without* the the "Learn More" link being present (seeing as it doesn't currently appear there anyway).

2. Wait until we've had a chance to add the link (which most likely will involve a front-end code change), and we do a coordinated push to production with those changes. I am somewhat weary of doing this seeing as that list is already very long, and might get cut off in the modal window for some users with lower resolution display settings.

**Comment by melwoodard** [comment] 2017-11-17 17:11
I'd suggest that if the link to be added only pertains to this specific school (which it appears to), it would be better to display that link directly in the caution flag rather than in the overlay, like so (the "More information on Ashford University" link):

![image](https://user-images.githubusercontent.com/4106356/32959664-2ec1dffe-cb77-11e7-9156-3cc24580ecc9.png)

**Comment by SPriceVA** [comment] 2017-11-17 17:21
Hey, we attempted to add the link before submitting the ticket and was unable. We asked for our permissions to be expanded so we can do quick fixes like this. if you can add the link or help us do it. that would be greatly appreciated.

**Comment by saneshark** [comment] 2017-11-20 19:47
@SPriceVA we're going to target for making the F/E UI changes to add the the link and information for this institution only. Similarly we're going to take the IOWA one out of the modal that appears when clicking "Learn more about these warnings" and show it similarly to the description that @melwoodard has written up above.

The idea is that institution specific caution flags should only appear for the institution in question, and the more generic caution flags will appear in the "Learn more about these warnings" modal.

In the future we could look at adding functionality whereby admins have permissions to update the Learn More details, but that will be out of scope for changes we can complete this week. In the meantime, please feel free to upload the CSV in settlements to support this on your end. It will be irrelevant to the F/E changes (the links will show up sometime later in the week when we can make the F/E change). Is that satisfactory?

**Comment by saneshark** [comment] 2017-11-20 19:50
The problem is that the "Learn more about these warnings" modal is getting quite long, and is not going to be a good UI experience. Ideally this list gets generated dynamically for each institution, but that is a much bigger change than adding the institution specific language at this time.

**Comment by SPriceVA** [comment] 2017-11-20 21:30
I agree it is definitely to long.

Thank you for adding the link for the one school.

**Closed as completed** 2017-11-27 21:13 UTC
